language: java
before_install:
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-actors.git
- cd vlingo-common && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}
script:
- mvn install
deploy:
  provider: bintray
  file: bintray.json
  skip_cleanup: true
  user: d-led
  on:
    branch: master
  key:
    secure: j2U/csEhX6St9vYPyu4PkP41tdTdk2maYv0SOcl3A6srp9ZjbUaq0YB77gW/HnDrdf8A3cns+BFV01qrtyQ8UkIiJ7n3kyimCjAcWiNNCM0ASZblaJGxHh80yS8OGPJgVPt9+jNQW+Gba27e1GvAawWnUV/Q/XFk7thOkufThF45+3MRlrdLfWVdukYEtls5c1FJkR5+FK9AlxxRNOgexp6UzalBZmS7tQkfW2jQzHrxJmRTqMwNcY6jH0fFicIwJEbl5xnMMm768kT8NI2jJRayT2HfJHJ33zNswRNM5jAX8TS5V9aE6nJTmw3/FjHLXKXHdudEOTOTy44WiLm01k4Pf5uHh1x18iWz3g8xl67WaXM4/mPMROefjcgpnDyigxX0q32Y0V61/vfwUAmP8xdN/T4M+hFVBZ1xYxsRCPVHLay9WkL+vRQo3O47MPfAJd5n8wbvzi7JRuQ6Xj/6K46RSXzlU5zFp+uXMcUvCo89oYvvrOc+DJqILucuQHG6kJg+4cv/tnwrzyU9XkpvO+keQJfhf/8n8A7Fl0q9uDOzYxI8GVkedQiVbukeh7uXjHRAPhhbvuLJv4RYqV9SFbd5fRiOin8Tfm4nmDeCIpOSWjJvLDh79yXV32yP04hKjYDuQ/G0NJ0QDDdxX7ya4Z5ucguytu6H9dRTr5qJlwc=
  passphrase:
    secure: jno/hK+LJjINavDAPfUnNcBtXYqih1HETU7TcaTJbo3zePzfXLJSx2YdVyXFRcf3yEnTIv2Ib7yyry3KSYBiMcZPFMOinP0jwERH+ylIfa0IsiEASwhytG1uTBiURhqQuLeST4FsL/sO/XEfGkfY585RzcnYEKyWpb59b69sqgs91T9uGZBDjnq+a1W+5qei02A63K+vK0vRzAFGhutLcSzIwgGnwjEDbXIXJnG9W9iuK9CGoGqIz50TCwWDek+gSNdTL5H/rjZqVPuIaetoqSd0kh3PFdkjSiHxQJ/mmNZWAM1o7H1TA+efywvCmKgan344d+LyKMkR3kVfb2yl7Rb0a2Bqd3g4+16omf0P53q1fZgPO+oRcXb6kC80jqKNGJX67sS8C1w1HpcVZp/tNuVmUzw/9/SmQ1G76IrWA3XTdmlgqvZUu+gH14dN24ofoBu6vWAmt2bKN3nBkp4Xck+eDnoe2zs6yaE0Q2WpM1ULLnpgzvxSlyGdJf2lf6w1DRoaoFF7B3cXqXMNF4X8N+rmJw8WcG4y7nndtuuIGxoCE+/aQWZCRB9Z7sByv2plaDuaXt/mgnA8lHCR/CZgAqgYRHHYEA9T8Jk+Fp20bC9kKd6j9Oa8kDaIpPQwy/I5jj536g/msctJykuFBh2nlJdCNFyVgX/xegDE2r0IC/g=
